services:
  apache:
    build: src/
    ports:
      - "80:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: urbanaut
      MARIADB_USER: urbanaut_user
      MARIADB_PASSWORD: urbanaut123
    ports:
    - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
