FROM mariadb:11

#le da el nombre a la base de dtos, el usuario, la contrasena y esas cosas 
ENV MARIADB_ROOT_PASSWORD=root_password
ENV MARIADB_DATABASE=urbanaut
ENV MARIADB_USER=urbanaut_user
ENV MARIADB_PASSWORD=urbanaur_password

#expone el puerto de mariadb
EXPOSE 3306
